version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: veera_postgres
    restart: always
    environment:
      POSTGRES_DB: claims_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
    ports:
      - "3813:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - veera_net

  backend:
    build: ./Backend
    container_name: veera_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3068:3068"
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: admin234
      PGDATABASE: claims_portal
      PGPORT: 5432
    volumes:
      - ./Backend/Uploads:/app/uploads
    networks:
      - veera_net

  frontend:
    build: ./Frontend
    container_name: veera_frontend
    ports:
      - "8071:80"
    networks:
      - veera_net

  hr:
    build: ./HR
    container_name: veera_hr
    ports:
      - "8072:80"
    networks:
      - veera_net

volumes:
  pgdata:

networks:
  veera_net:


